### ISSUE TITLE
Editor color theme changes on ever start

### ISSUE THREAD

**Issue by Lafreakshow** [ADMARIl/halcyon-jetbrains#11]
Hello there and thanks for bringing us this great theme!

Now, on to business. I understand that the plugin is supposed to force the correct color scheme on first run, which is a good thing. However, it's doing it every time I start IntelliJ for me. I would guess it has to do with me using a custom editor color scheme which is  a copy of the halcyon one with a few minor adjustments. Every time IntelliJ starts, the editor color scheme is changed back to the halcyon default.

Another mildly annoying thing here is that it's also happening when the halcyon UI theme isn't selected. Depending on lighting in my office I sometimes end up using a lighter theme instead and still on every start I have to adjust the editor color scheme. I would assume this qualifies as intended behavior though, and It's easy enough to just disable the halcyon plugin in this case.

Usually, I would try to suggest a solution but honestly I'm not quite sure what would be a good solution here. I assume the plugin currently checks if the correct scheme is selected? In that case, perhaps disabling the feature when the user changes away from the default might be an option. 

Let me know if you need any additional info or want me to test something.

**Comment by panckreous** [comment]
Same. Tested on Rubymine 2020.3, Webstorm 2021.2 EAP and AppCode 2021.1. I've been trying out a bunch of new themes and this is the only one that I've experienced do this. The only way I've been able to stop this is to disable or uninstall the plugin in each IDE. 

And not to parrot @Lafreakshow too much but this theme is indeed really good! High quality jetbrains themes are sadly pretty rare so most importantly thank you for your great work on this

**Comment by ADMARIl** [comment]
So the way the plug-in is written, it’s only supposed to force the styling the very first time the plug-in run. After this happens it’s supposed to store a Boolean flag inside of a plug-in settings xml file on the client machine. Then, each time the plug-in is launched it’ll [check to see if the flag is set](https://github.com/ADMARIl/halcyon-jetbrains/blob/796c60f5b3fa120c8eece284f790c97950d9cc2f/src/main/java/com/ADMARIl/halcyonjetbrains/HandleStartup/StartupWelcomeActivity.java#L17). I suspect the breakdown is happening in the _store the flag on the client_ step, since I haven’t been able to actually verify this was happening when testing the code. 

For now, would it be an acceptable decision to disable the forcing of the theme all together?

**Comment by Lafreakshow** [comment]
I can do perfectly without the forcing of the theme.

**Comment by panckreous** [comment]
For what it's worth I don't recall seeing any other plugins displaying messages like that - I totally get why you did and appreciate the thought you put into doing that as well (I find the way IDEA handles it all so muddled: themes vs color schemes and having them install as plugins vs configuration files etc)

I would vote to not worry about that at all and not override the color scheme in any instance. Also, there are times I mix and match the themes and color schemes since I find a handful of themes really good for the IDE skin. 

It's happening to me on three different IDEs - is there something I can test for you? Logs, etc? Definitely faster to just remove but it's your work that you care for so I'm happy to help if you'd like to try to debug...

(sidenote - can you recommend any resources that would help me understand theming in IDEA besides their official docs? I find those not as helpful as they could be)

**Comment by ADMARIl** [comment]
I've published a new release of the theme to JetBrains for their approval. You can [see the update here](https://plugins.jetbrains.com/plugin/14093-halcyon-theme/versions/stable/122413). For the time being, I've commented out the section of the startup activity that forces the plugin scheme. I've left a branch, `theme_force` with the original code in case the underlying issue can be determined.

@panckreous Regarding documentation and resources, outside of JetBrains' official docs, the only other resource I could find was looking through the source code for other published plugins to see how they did things.

**Comment by Lafreakshow** [comment]
@panckreous To add my experience with the IntelliJ Platform in general (I worked on some plugins, but haven't done themes) I'm with @ADMARIl  here. I found it really hard to find decent resources. The Official documentation is the best available resource for the things covered in it and for things not covered by Jetbrains I found myself looking at plugins that I thought would be doing something similar and trying to figure out how they achieve it. I also found myself just browsing the IntelliJ platform source and simply experimenting a whole lot. 

That is unfortunately the most effective way of learning how things work I've found. A lot of what I needed I managed by looking at the source of official Jetbrains plugins and then piecing together and adapting what they did.
Sidenote: I think this is a major reason for why there are so comparatively few Themes/Plugins. It's just really inconvenient, frustrating and time consuming to make them so the ones we get are probably either Commercial products or (like what I did) passion projects. Which is a shame really because I found the IntelliJ Platform to be incredibly powerful and it would probably be really nice to work with if there was better documentation. Doesn't help that a lot of the source code isn't commented particularly well either. Also makes maintenance hard because it's difficult to figure out what the current best practice is.

And to get back on topic just a bit: Thanks for the very quick response, @ADMARIl. Always appreciate your responsiveness. I think might have said that last time I had an issue with Halcyon too, but who cares. Maintainers get way too little appreciation. Should my masochism resurface in the near future, I may look into this issue. Perhaps I can figure out what's wrong.
